import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import { Geist } from "next/font/google";
import "./globals.css";
import gallery from "@/data/gallery.json";
import type { GalleryEntry } from "@/lib/gallery";
import { CommandPalette, CommandPaletteButton } from "@/components/CommandPalette";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Jev as a Judge",
  description: "Feed Jev a case record and get a ruling with confidence.",
};

const NAV = [
  ["/", "Courtroom"],
  ["/gallery", "Gallery"],
] as const;

export default function RootLayout({ children }: LayoutProps<"/">) {
  const entries = gallery as GalleryEntry[];
  return (
    <html lang="en" className={`${geistSans.variable} h-full antialiased`}>
      <body className="flex min-h-full flex-col">
        <header className="wood sticky top-0 z-40 shadow-md">
          <nav className="mx-auto flex max-w-6xl items-center gap-6 px-6 py-2.5">
            <Link href="/" className="flex items-center gap-2.5">
              <span className="brass flex h-7 w-7 items-center justify-center rounded-full">
                <Image src="/typesafe-mark.png" alt="" width={16} height={16} className="opacity-90" />
              </span>
              <span className="font-serif text-lg text-brass-light">Jev as a Judge</span>
            </Link>
            <div className="hidden items-center gap-5 sm:flex">
              {NAV.map(([href, label]) => (
                <Link
                  key={href}
                  href={href}
                  className="text-sm text-oak-300/90 hover:text-brass-light"
                >
                  {label}
                </Link>
              ))}
            </div>
            <div className="ml-auto">
              <CommandPaletteButton />
            </div>
          </nav>
          <div className="wood-rail" />
        </header>
        <main className="mx-auto w-full max-w-6xl flex-1 px-6 py-8">{children}</main>
        <footer className="px-6 py-6 text-center text-xs text-wall/70">
          Rulings are generated by TypeSafe&apos;s Jev from the case record alone and are an experiment,
          not legal advice.
        </footer>
        <CommandPalette entries={entries} />
      </body>
    </html>
  );
}
